"""Discovery of site-specific Jira IDs into `config/jira_ids.yaml` (PRD 0.3, 7.3).

Fields are matched by name. Team-managed projects scope custom fields to the project,
so a field scoped to this project wins over a global field with the same name.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from codeit.jira_client.client import API, JiraClient
from codeit.jira_client.models import REQUIRED_FIELDS, FieldMap, JiraIds
from codeit.jira_client.search import search
from codeit.jira_client.transitions import list_transitions

DEFAULT_IDS_PATH = Path("config/jira_ids.yaml")


class DiscoveryError(Exception):
    def __init__(self, problems: list[str]) -> None:
        super().__init__("; ".join(problems))
        self.problems = problems


@dataclass
class ProjectInfo:
    id: str
    key: str
    name: str
    style: str
    issue_types: dict[str, str] = field(default_factory=dict)


async def get_project(client: JiraClient, project_key: str) -> ProjectInfo:
    raw = await client.get_json(f"{API}/project/{project_key}")
    return ProjectInfo(
        id=str(raw["id"]),
        key=str(raw["key"]),
        name=str(raw.get("name") or ""),
        style=str(raw.get("style") or ""),
        issue_types={str(t["name"]): str(t["id"]) for t in raw.get("issueTypes") or []},
    )


async def get_statuses(client: JiraClient, project_key: str) -> dict[str, str]:
    """Status name -> ID across all issue types of the project."""
    raw = await client.get_json(f"{API}/project/{project_key}/statuses")
    out: dict[str, str] = {}
    for issue_type in raw:
        for status in issue_type.get("statuses") or []:
            out.setdefault(str(status["name"]), str(status["id"]))
    return out


def resolve_fields(
    all_fields: list[dict[str, Any]], project_id: str
) -> tuple[dict[str, str], list[str]]:
    """Map FieldMap attributes to field IDs. Returns (found, problems)."""
    found: dict[str, str] = {}
    problems: list[str] = []
    for attr, names in REQUIRED_FIELDS.items():
        wanted = {n.casefold() for n in names}
        candidates = [f for f in all_fields if str(f.get("name", "")).casefold() in wanted]
        scoped = [f for f in candidates if _scope_project(f) == project_id]
        unscoped = [f for f in candidates if _scope_project(f) is None]
        best = scoped or unscoped
        label = " or ".join(repr(n) for n in names)
        if not best:
            problems.append(f"field {label} not found")
        elif len(best) > 1:
            ids = ", ".join(str(f["id"]) for f in best)
            problems.append(f"field {label} is ambiguous: {ids}")
        else:
            found[attr] = str(best[0]["id"])
    return found, problems


def _scope_project(f: dict[str, Any]) -> str | None:
    scope = f.get("scope") or {}
    if scope.get("type") != "PROJECT":
        return None
    return str((scope.get("project") or {}).get("id"))


async def sample_transitions(client: JiraClient, project_key: str) -> dict[str, str]:
    """Transition IDs from the newest issue in the project; empty if it has no issues."""
    async for issue in search(
        client, f"project = {project_key} ORDER BY created DESC", ["status"], max_results=1
    ):
        return {t.to_status: t.id for t in await list_transitions(client, issue["key"])}
    return {}


async def discover(client: JiraClient, project_key: str) -> JiraIds:
    """Collect every ID CodeIt needs. Raises `DiscoveryError` listing what is missing."""
    project = await get_project(client, project_key)
    all_fields = await client.get_json(f"{API}/field")
    field_ids, problems = resolve_fields(all_fields, project.id)
    if problems:
        raise DiscoveryError(problems)
    return JiraIds(
        fields=FieldMap(**field_ids),
        statuses=await get_statuses(client, project_key),
        issue_types=project.issue_types,
        transitions=await sample_transitions(client, project_key),
    )


_HEADER = "# Generated by `codeit jira discover`. Rerun it instead of editing by hand.\n"


def write_ids(ids: JiraIds, path: Path = DEFAULT_IDS_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(ids.model_dump(), sort_keys=False, allow_unicode=True)
    path.write_text(_HEADER + body, encoding="utf-8")


def load_ids(path: Path = DEFAULT_IDS_PATH) -> JiraIds:
    if not path.exists():
        raise FileNotFoundError(f"{path} not found; run `codeit jira discover` first")
    return JiraIds.model_validate(yaml.safe_load(path.read_text(encoding="utf-8")))
