from __future__ import annotations

from pathlib import Path

import httpx
import pytest
import respx

from codeit.jira_client import JiraClient
from codeit.jira_client.discover import (
    DiscoveryError,
    discover,
    load_ids,
    resolve_fields,
    write_ids,
)
from codeit.jira_client.doctor import Check, run_doctor
from tests.unit.jira.fake_site import CUSTOM, PROJECT_ID, STORY_ID, FakeSite, scoped


@pytest.fixture
def site(mock: respx.MockRouter) -> FakeSite:
    return FakeSite(mock).install()


def by_name(checks: list[Check]) -> dict[str, Check]:
    return {c.name: c for c in checks}


# discover ---------------------------------------------------------------------------------------


async def test_discover_collects_ids(site: FakeSite, client: JiraClient) -> None:
    ids = await discover(client, "CODEIT")
    assert ids.fields.story_points == "customfield_10016"
    assert ids.fields.agent == CUSTOM["Agent"]  # project-scoped wins over another project's
    assert ids.statuses["Human Review"] == "6"
    assert ids.statuses["Done"] == "7"  # the Story's, not the Epic's
    assert "In Progress" not in ids.statuses
    assert ids.issue_type_id("story") == STORY_ID
    assert ids.transitions["Done"] == "25"


async def test_discover_without_issues_has_no_transitions(
    site: FakeSite, client: JiraClient
) -> None:
    site.issues = []
    ids = await discover(client, "CODEIT")
    assert ids.transitions == {}


async def test_discover_reports_missing_fields(site: FakeSite, client: JiraClient) -> None:
    site.fields = [f for f in site.fields if f["name"] != "PR URL"]
    with pytest.raises(DiscoveryError) as err:
        await discover(client, "CODEIT")
    assert err.value.problems == ["field 'PR URL' not found"]


def test_resolve_fields_ambiguous_and_global_fallback() -> None:
    fields = [
        {"id": "customfield_1", "name": "Story Points"},
        scoped("customfield_2", "Agent"),
        scoped("customfield_3", "Agent"),
        {"id": "customfield_4", "name": "Review Loop"},
    ]
    found, problems = resolve_fields(fields, PROJECT_ID)
    assert found["story_points"] == "customfield_1"
    assert found["review_loop"] == "customfield_4"
    assert "field 'Agent' is ambiguous: customfield_2, customfield_3" in problems


async def test_ids_round_trip_through_yaml(
    site: FakeSite, client: JiraClient, tmp_path: Path
) -> None:
    ids = await discover(client, "CODEIT")
    path = tmp_path / "config" / "jira_ids.yaml"
    write_ids(ids, path)
    assert path.read_text().startswith("# Generated by `codeit jira discover`")
    assert load_ids(path) == ids


def test_load_ids_missing_file(tmp_path: Path) -> None:
    with pytest.raises(FileNotFoundError, match="codeit jira discover"):
        load_ids(tmp_path / "nope.yaml")


def test_issue_type_id_unknown(tmp_path: Path) -> None:
    from codeit.jira_client.models import JiraIds
    from tests.unit.jira.conftest import FIELDS

    ids = JiraIds(fields=FIELDS, statuses={}, issue_types={})
    with pytest.raises(KeyError, match="discover"):
        ids.issue_type_id("Story")


# doctor -----------------------------------------------------------------------------------------


async def test_doctor_all_pass(site: FakeSite, client: JiraClient) -> None:
    checks = await run_doctor(client, "CODEIT")
    assert [c.name for c in checks] == ["auth", "project", "statuses", "fields", "transitions"]
    assert all(c.ok for c in checks), checks
    assert "CodeIt Bot" in checks[0].detail


async def test_doctor_bad_auth_stops(mock: respx.MockRouter, client: JiraClient) -> None:
    mock.get("/myself").respond(401)
    checks = await run_doctor(client, "CODEIT")
    assert [(c.name, c.ok) for c in checks] == [("auth", False)]
    assert "JIRA_API_TOKEN" in checks[0].hint


async def test_doctor_unreachable_site(mock: respx.MockRouter, client: JiraClient) -> None:
    mock.get("/myself").mock(side_effect=httpx.ConnectError("dns"))
    checks = await run_doctor(client, "CODEIT")
    assert [(c.name, c.ok) for c in checks] == [("auth", False)]
    assert "JIRA_BASE_URL" in checks[0].hint


async def test_doctor_missing_project_stops(mock: respx.MockRouter, client: JiraClient) -> None:
    mock.get("/myself").respond(json={"displayName": "Bot"})
    mock.get("/project/CODEIT").respond(404)
    checks = await run_doctor(client, "CODEIT")
    assert [(c.name, c.ok) for c in checks] == [("auth", True), ("project", False)]


async def test_doctor_reports_missing_status_and_field(site: FakeSite, client: JiraClient) -> None:
    site.statuses = [s for s in site.statuses if s != "Agent Review"]
    site.story_fields.discard(CUSTOM["Run ID"])
    checks = by_name(await run_doctor(client, "CODEIT"))
    assert not checks["statuses"].ok
    assert "Agent Review" in checks["statuses"].detail
    assert not checks["fields"].ok
    assert "run_id" in checks["fields"].detail
    assert "PRD 7.1" in checks["fields"].hint


async def test_doctor_reports_unreachable_transitions(site: FakeSite, client: JiraClient) -> None:
    site.reachable = ["In Dev"]
    checks = by_name(await run_doctor(client, "CODEIT"))
    assert not checks["transitions"].ok
    assert "Done" in checks["transitions"].detail
    assert "Allow all statuses" in checks["transitions"].hint


async def test_doctor_skips_transitions_without_issues(site: FakeSite, client: JiraClient) -> None:
    site.issues = []
    checks = by_name(await run_doctor(client, "CODEIT"))
    assert checks["transitions"].ok
    assert "skipped" in checks["transitions"].detail


async def test_doctor_write_test(site: FakeSite, client: JiraClient) -> None:
    checks = by_name(await run_doctor(client, "CODEIT", write_test=True))
    assert checks["write"].ok
    assert "CODEIT-99" in checks["write"].detail
    assert "CODEIT-99" in checks["transitions"].detail


async def test_doctor_write_test_delete_denied(site: FakeSite, client: JiraClient) -> None:
    site.delete_route.respond(403)
    checks = by_name(await run_doctor(client, "CODEIT", write_test=True))
    assert not checks["write"].ok
    assert "delete CODEIT-99 by hand" in checks["write"].hint


async def test_doctor_write_test_create_denied(site: FakeSite, client: JiraClient) -> None:
    site.create_route.respond(403)
    checks = by_name(await run_doctor(client, "CODEIT", write_test=True))
    assert not checks["write"].ok
    assert "create failed" in checks["write"].detail
