"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-09-24 23:45:51.776504
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_instances",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("current_run_id", sa.String(length=26), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "backend_state",
        sa.Column("backend", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("parked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("backend"),
    )
    op.create_table(
        "budget_ledger",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("backend", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("key_name", sa.String(length=64), nullable=True),
        sa.Column("usd", sa.Float(), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("budget_ledger", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_budget_ledger_ts"), ["ts"], unique=False)

    op.create_table(
        "eval_runs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("suite", sa.String(length=64), nullable=False),
        sa.Column("config_name", sa.String(length=64), nullable=False),
        sa.Column("steering_sha", sa.String(length=40), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leases",
        sa.Column("ticket_key", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("instance", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("ticket_key"),
    )
    with op.batch_alter_table("leases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_leases_expires_at"), ["expires_at"], unique=False)

    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("instance", sa.String(length=64), nullable=False),
        sa.Column("ticket_key", sa.String(length=32), nullable=True),
        sa.Column("backend", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("steering_sha", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("turns", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("transcript_path", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_role"), ["role"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_ticket_key"), ["ticket_key"], unique=False)

    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("ticket_key", sa.String(length=32), nullable=True),
        sa.Column("pr", sa.Integer(), nullable=True),
        sa.Column("author", sa.String(length=128), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("theme", sa.String(length=32), nullable=True),
        sa.Column("lesson", sa.Text(), nullable=True),
        sa.Column("used_in_learning_run", sa.String(length=26), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_signals_ticket_key"), ["ticket_key"], unique=False)

    op.create_table(
        "tickets_cache",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=True),
        sa.Column("points", sa.Float(), nullable=True),
        sa.Column("review_loop", sa.Integer(), nullable=False),
        sa.Column("human_returns", sa.Integer(), nullable=False),
        sa.Column("pr_url", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("tickets_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tickets_cache_status"), ["status"], unique=False)

    op.create_table(
        "eval_results",
        sa.Column("eval_run_id", sa.String(length=26), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("repeat_idx", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("hidden_pass_ratio", sa.Float(), nullable=True),
        sa.Column("turns", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("diff_lines", sa.Integer(), nullable=True),
        sa.Column("reviewer_verdict", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["eval_run_id"],
            ["eval_runs.id"],
        ),
        sa.PrimaryKeyConstraint("eval_run_id", "task_id", "repeat_idx"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_ts"), ["ts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_ts"))
        batch_op.drop_index(batch_op.f("ix_events_run_id"))

    op.drop_table("events")
    op.drop_table("eval_results")
    with op.batch_alter_table("tickets_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tickets_cache_status"))

    op.drop_table("tickets_cache")
    with op.batch_alter_table("signals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signals_ticket_key"))

    op.drop_table("signals")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_ticket_key"))
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_role"))

    op.drop_table("runs")
    with op.batch_alter_table("leases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leases_expires_at"))

    op.drop_table("leases")
    op.drop_table("eval_runs")
    with op.batch_alter_table("budget_ledger", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budget_ledger_ts"))

    op.drop_table("budget_ledger")
    op.drop_table("backend_state")
    op.drop_table("agent_instances")
    # ### end Alembic commands ###
