"""mcp run tokens

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 02:15:17.302462
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("ticket_key", sa.String(length=32), nullable=True),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("mcp_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mcp_tokens_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_mcp_tokens_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mcp_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mcp_tokens_run_id"))
        batch_op.drop_index(batch_op.f("ix_mcp_tokens_expires_at"))

    op.drop_table("mcp_tokens")
    # ### end Alembic commands ###
